# Appendices {-}
## Appendix 1: example structured consent page

Thank you for taking the time to consider helping in this research,
which is being conducted by Student Name and Jon May from the University
of Plymouth. Please read the below information before deciding whether
or not to take part. Continue to the next page once you have read all of
the information.

**What is the study about?**

Goal achievement is a big aspect of people’s lives, especially when
involved in sports. It has been suggested that there are links between
motivation and goal achievement in certain sports. This study aims to
investigate these links, and whether or not it is linked with the
personality trait Grit.

**What will I have to do if I take part?**

This survey consists of several pages which contains rating scales about
your attitudes towards taking part in sport. Some of the questions are
novel, but most are based on existing and tested questionnaires. You
will be asked to report your age and sex so that we can ensure our
sample is representative of the population. We have tested this survey
and it should take you no longer than **ten minutes** to complete.

**Will the information collected during the study be kept
confidential?**

The study will be conducted in accordance with the General Data
Protection Regulation (2018) and the guidelines of the British
Psychological Society. All information collected about you during the
study will be anonymised. Your personal details will be stored securely
at the University of Plymouth, accessible only by members of the study
team. When this project is being written up, no identifying information
will be used.

**What are the benefits and risks of taking part in this study?**

There are no direct benefits of taking part in this study. You will not
receive any motivational training as part of this study, but the results
may influence training that may be made available in the future. There
should be no risks involved with taking part in this study.

**What if I have more questions?**

If you have any more questions or don’t quite understand something
regarding this study then please email Student Name at
student.name@students.plymouth.ac.uk. If they cannot answer your
questions satisfactorily, then you can contact the Research Supervisor,
Professor Jon May,
at jon.may@plymouth.ac.uk, or the Faculty Ethical Committee directly at
hhsethics@plymouth.ac.uk.

**What happens now if you don’t want to take part?**

Your participation is voluntary so you do not have to take part, nor do
you have to give a reason why. If you don’t choose to take part this
will not affect any further opportunities that may arise. Simply close
this window. You can also stop at any point in this survey by closing
the browser window.

Thank you for considering taking part in this project.

## Appendix 2: codes for piping from different question types

<table>
<colgroup>
<col style="width: 48%" />
<col style="width: 51%" />
</colgroup>
<thead>
<tr>
<th style="text-align: center;">**Question code name<br />
**(e.g., for an Array type named qArray with subquestions F1 to
F3)</th>
<th style="text-align: center;">**Piping text to use<br />
**(e.g., to show the chosen or entered answer, insert this
text)</th>
</tr>
</thead>
<tbody>
<tr>
<td>qArray_F1</td>
<td>{qArray_F1.shown}</td>
</tr>
<tr>
<td>qArray_F2</td>
<td>{qArray_F2.shown}</td>
</tr>
<tr>
<td>qArray_F3</td>
<td>{qArray_F3.shown}</td>
</tr>
<tr>
<td>q5pointChoice</td>
<td>{q5pointChoice.shown}</td>
</tr>
<tr>
<td>qListDropdown</td>
<td>{qListDropdown.shown}</td>
</tr>
<tr>
<td>qListDropdown_other</td>
<td>{qListDropdown_other.shown}</td>
</tr>
<tr>
<td>qListRadio</td>
<td>{qListRadio.shown}</td>
</tr>
<tr>
<td>qListRadio_other</td>
<td>{qListRadio_other.shown}</td>
</tr>
<tr>
<td>qListWithComment</td>
<td>{qListWithComment.shown}</td>
</tr>
<tr>
<td>qListWithComment_comment</td>
<td>{qListWithComment_comment.shown}</td>
</tr>
<tr>
<td>qArray10Point_L1</td>
<td>{qArray10Point_L1.shown}</td>
</tr>
<tr>
<td>qArray10Point_L2</td>
<td>{qArray10Point_L2.shown}</td>
</tr>
<tr>
<td>qArray10Point_L3</td>
<td>{qArray10Point_L3.shown}</td>
</tr>
<tr>
<td>qArray5Point_1</td>
<td>{qArray5Point_1.shown}</td>
</tr>
<tr>
<td>qArray5Point_2</td>
<td>{qArray5Point_2.shown}</td>
</tr>
<tr>
<td>qArray5Point_3</td>
<td>{qArray5Point_3.shown}</td>
</tr>
<tr>
<td>qArrayISD_1</td>
<td>{qArrayISD_1.shown}</td>
</tr>
<tr>
<td>qArrayISD_2</td>
<td>{qArrayISD_2.shown}</td>
</tr>
<tr>
<td>qArrayISD_3</td>
<td>{qArrayISD_3.shown}</td>
</tr>
<tr>
<td>qArrayNumbers_list1_min</td>
<td>{qArrayNumbers_list1_min.shown}</td>
</tr>
<tr>
<td>qArrayNumbers_list1_max</td>
<td>{qArrayNumbers_list1_max.shown}</td>
</tr>
<tr>
<td>qArrayNumbers_list1_avg</td>
<td>{qArrayNumbers_list1_avg.shown}</td>
</tr>
<tr>
<td>qArrayTexts_hp_1st</td>
<td>{qArrayTexts_hp_1st.shown}</td>
</tr>
<tr>
<td>qArrayTexts_hp_2nd</td>
<td>{qArrayTexts_hp_2nd.shown}</td>
</tr>
<tr>
<td>qArrayTexts_hp_3rd</td>
<td>{qArrayTexts_hp_3rd.shown}</td>
</tr>
<tr>
<td>qArrayYNU_1</td>
<td>{qArrayYNU_1.shown}</td>
</tr>
<tr>
<td>qArrayYNU_2</td>
<td>{qArrayYNU_2.shown}</td>
</tr>
<tr>
<td>qArrayYNU_3</td>
<td>{qArrayYNU_3.shown}</td>
</tr>
<tr>
<td>qArrayByColumn_1</td>
<td>{qArrayByColumn_1.shown}</td>
</tr>
<tr>
<td>qArrayByColumn_2</td>
<td>{qArrayByColumn_2.shown}</td>
</tr>
<tr>
<td>qArrayByColumn_3</td>
<td>{qArrayByColumn_3.shown}</td>
</tr>
<tr>
<td>qArrayDualScale_money_0</td>
<td>{qArrayDualScale_money_0.shown}</td>
</tr>
<tr>
<td>qArrayDualScale_money_1</td>
<td>{qArrayDualScale_money_1.shown}</td>
</tr>
<tr>
<td>qDate</td>
<td>{qDate.shown}</td>
</tr>
<tr>
<td>qFileUpload</td>
<td>{qFileUpload.shown}</td>
</tr>
<tr>
<td>qFileUpload_filecount</td>
<td>{qFileUpload_filecount.shown}</td>
</tr>
<tr>
<td>qGender</td>
<td>{qGender.shown}</td>
</tr>
<tr>
<td>qLanguage</td>
<td>{qLanguage.shown}</td>
</tr>
<tr>
<td>qMultipleNumerical_self</td>
<td>{qMultipleNumerical_self.shown}</td>
</tr>
<tr>
<td>qMultipleNumerical_mom</td>
<td>{qMultipleNumerical_mom.shown}</td>
</tr>
<tr>
<td>qMultipleNumerical_dad</td>
<td>{qMultipleNumerical_dad.shown}</td>
</tr>
<tr>
<td>qNumerical</td>
<td>{qNumerical.shown}</td>
</tr>
<tr>
<td>qRanking_1</td>
<td>{qRanking_1.shown}</td>
</tr>
<tr>
<td>qRanking_2</td>
<td>{qRanking_2.shown}</td>
</tr>
<tr>
<td>qRanking_3</td>
<td>{qRanking_3.shown}</td>
</tr>
<tr>
<td>qTextDisplay</td>
<td>{qTextDisplay.shown}</td>
</tr>
<tr>
<td>qYesNo</td>
<td>{qYesNo.shown}</td>
</tr>
<tr>
<td>qHugeText</td>
<td>{qHugeText.shown}</td>
</tr>
<tr>
<td>qLongText</td>
<td>{qLongText.shown}</td>
</tr>
<tr>
<td>qMultipleShort_friend</td>
<td>{qMultipleShort_friend.shown}</td>
</tr>
<tr>
<td>qMultipleShort_family</td>
<td>{qMultipleShort_family.shown}</td>
</tr>
<tr>
<td>qMultipleShort_work</td>
<td>{qMultipleShort_work.shown}</td>
</tr>
<tr>
<td>qShort</td>
<td>{qShort.shown}</td>
</tr>
<tr>
<td>qMultipleChoice_Hawaii</td>
<td>{qMultipleChoice_Hawaii.shown}</td>
</tr>
<tr>
<td>qMultipleChoice_Bahamas</td>
<td>{qMultipleChoice_Bahamas.shown}</td>
</tr>
<tr>
<td>qMultipleChoice_Europe</td>
<td>{qMultipleChoice_Europe.shown}</td>
</tr>
<tr>
<td>qMultChoiceComment_junk</td>
<td>{qMultChoiceComment_junk.shown}</td>
</tr>
<tr>
<td>qMultChoiceComment_junkcomment</td>
<td>{qMultChoiceComment_junkcomment.shown}</td>
</tr>
<tr>
<td>qMultChoiceComment_rtv</td>
<td>{qMultChoiceComment_rtv.shown}</td>
</tr>
<tr>
<td>qMultChoiceComment_rtvcomment</td>
<td>{qMultChoiceComment_rtvcomment.shown}</td>
</tr>
<tr>
<td>qMultChoiceComment_ex</td>
<td>{qMultChoiceComment_ex.shown}</td>
</tr>
<tr>
<td>qMultChoiceComment_excomment</td>
<td>{qMultChoiceComment_excomment.shown}</td>
</tr>
</tbody>
</table>

## Appendix3: expression script examples

<https://manual.limesurvey.org/ExpressionScript_examples/en>

